name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Jupyter Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --execute --to notebook --inplace <The Rise of Artificial Intelligence Trends, Impact and Insights.ipynb>.ipynb
